### ISSUE TITLE
[Wiki] Error using the provided postfix in section 1.4

### ISSUE THREAD

**Issue by Owen3H** [BepInEx/HarmonyX#102]
![image](https://github.com/BepInEx/HarmonyX/assets/48495634/e0e68473-1e07-4d61-bb30-4af147ad6a28)
The `foreach` loop here throws [CS1579](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1579?f1url=%3FappId%3Droslyn%26k%3Dk(CS1579)).

![image](https://github.com/BepInEx/HarmonyX/assets/48495634/8acf28af-a2aa-4cf1-b1f5-1172f34585bf)

Instead, replace it with something like the following:
```cs
while (result.MoveNext())
    yield return result.Current;
```

**Comment by ManlyMarco** [comment]
Fixed, thanks.
