### ISSUE TITLE
How do I find the asset directory of stuff stored in a unity game?

### ISSUE THREAD

**Issue by grossbacher** [BepInEx/HarmonyX#110]
I've looked FAR AND WIDE and just can't figure out how people know what file directory stuff is stored in. (For example, Assets/Prefabs/Enemies/SisyphusPrime.prefab). Is there a specific program you have to use? Assetripper doesn't give you the same file structure as the base game.

**Comment by ManlyMarco** [comment]
It depends on engine version, ask on the BepInEx server.
