### ISSUE TITLE
Add an overload for `Harmony.PatchAll()` with a callback to verify each method/class?

### ISSUE THREAD

**Issue by Sombody101** [BepInEx/HarmonyX#120]
This is more of a specific enhancement request, but could a quick-and-dirty overload be added for `Harmony.PatchAll()` that introduces a `Func<MethodInfo, bool>` callback to allow users to stop a method from being patched without making a custom patcher backend or patching and then unpatching it manually?

This is what I had in mind:
```c#
public void PatchAll(Assembly assembly, Func<MethodInfo, bool> validationCallback)

...

Harmony harmony = new Harmony(GUID);
harmony.PatchAll(typeof(Plugin).Assembly, (MethodInfo originalMethod) => 
{
    return /* Some check or configuration */;
});
```

Or, if an enum was used rather than a bool:
```c#
public void PatchAll(Assembly assembly, Func<MethodInfo, MethodValidation> validationCallback)

...

Harmony harmony = new Harmony(GUID);
harmony.PatchAll(typeof(Plugin).Assembly, (MethodInfo originalMethod) => 
{
    if (/* Some check or configuration */)
    {
        return MethodValidation.NoPatch;
    }
    else
    {
        // ...
    }
    
    return MethodValidation.PatchMethod;
});
```

**Comment by CptMoore** [comment]
Why not return false in the Prepare method of a Patch?
That will already skip that patch.

```csharp
[HarmonyPatch(typeof(SqliteCommand), nameof(SqliteCommand.CommandText), MethodType.Setter)]
internal static class SqliteCommand_CommandText_Setter_Patch
{
    public static bool Prepare()
    {
        return ModTek.Enabled && ModTek.Config.Logging.LogSqlQueryInitializations;
    }
```

**Comment by Sombody101** [comment]
I was thinking of something that would apply to all methods regardless of the class's implementation of `Prepare()`.

In the project I'm making, I can add a custom attribute to methods that affect whether the target method is patched at runtime, but I want the patching to be done from a single point. My specific case also deals with types that are defined in an optional DLL, so I want to reduce the number of errors that can occur if a user uses my mod without the other optional DLL.

So, it's a single action that I need to apply to all patch methods.

**Comment by ManlyMarco** [comment]
Not sure how useful this would be to add. There's already #105 that you can use to handle missing target methods.

**Comment by Sombody101** [comment]
That works, thanks!
