### ISSUE TITLE
[Documentation] Broken Link

### ISSUE THREAD

**Issue by marwie** [BepInEx/HarmonyX#23]
This link here does not work anymore

![image](https://user-images.githubusercontent.com/5083203/111868504-8bd5eb80-897a-11eb-8696-57419188f076.png)

https://github.com/BepInEx/BepInEx/blob/framework-il2cpp/BepInEx.IL2CPP/Hook/IL2CPPDetourMethodPatcher.cs

Wiki Site:
https://github.com/BepInEx/HarmonyX/wiki/Custom-MethodPatcher

Should point to here I guess: https://github.com/BepInEx/BepInEx/blob/ff4e1b7c7f40dbc812cb25c979fd946c5b7e0479/BepInEx.IL2CPP/Hook/IL2CPPDetourMethodPatcher.cs

**Comment by ghorsington** [comment]
Thanks for the report! Fixed it and updated it to link to the latest version of Il2Cpp patching backend.
