### ISSUE TITLE
How to add this to unity?

### ISSUE THREAD

**Issue by friuns2** [BepInEx/HarmonyX#33]
I added dll to unity but i get errors like 

Assembly 'Assets/Packages/HarmonyX.2.5.5/lib/netstandard2.0/0Harmony.dll' will not be loaded due to errors:  
Unable to resolve reference 'MonoMod.Utils'. Is the assembly missing or incompatible with the current platform?

**Comment by ghorsington** [comment]
Marking this as resolved since we don't have any plans or need for packages aimed at Unity editor. If you need HarmonyX there, you can reference the assemblies manually. That said, we'll take a PR if someone does want to make a Unity-specific packaging for HarmonyX
