### ISSUE TITLE
Port Harmony 2 API

### ISSUE THREAD

**Issue by denikson** [BepInEx/HarmonyX#4]
Port latest stable Harmony 2 once it's finished.

Here are notes on current important changes to keep track of:

**[798915](https://github.com/pardeike/Harmony/commit/798915f9e40347f48c4e7cbcd5db4c97b5101585)**
* New `PatchJobs` and `PatchClassProcessor` API
    * Wait until properly implemented
    * Simplify into `PatchCollection` (internal, maybe not needed)
    * Make `PatchClassProcessor` inherit `PatchProcessorBase` and make method patch processor its own class
* `public PatchProcessor ProcessorForAnnotatedClass` => `public PatchClassProcessor ProcessorForAnnotatedClass`
    * Not used by old API, can be replaced
* `Harmony.GetPatchedMethods` and `Harmony.VersionInfo` route to `PatchProcessor.GetAllPatchedMethods` and `PatchProcessor.VersionInfo`
    * New API public, has to be included
* New: `HarmonyMethod.GetMergedFromType` and `HarmonyMethod.GetMergedFromMethod`
    * Both public, port
* `PatchProcessor` simplified
    * `AllPatchedMethods` => `GetAllPatchedMethods`
    * Type ctor overload got removed, make it proxy `PatchClassProcessor`
    * Added `GetPatchInfo` from `Harmony.GetPatchInfo`
* `AccessTools`
    * `AccessTools.IsDeclaredMember` and `AccessTools.GetDeclaredMember`
    * `*Constructor*` methods have new parameter => add new overloads
* New tests

**[687ed73](https://github.com/pardeike/Harmony/commit/687ed73eac9e23b01a30758c97140707add71152)**
* `Traverse.PropertyExists`

**[MonoMod.Common PR](https://github.com/pardeike/Harmony/pull/239)**
* All public methods that returned `DynamicMethod` return `MethodInfo` instead
    * Add new overloads, obsolete old overloads
    * [Update MethodInfo generator](https://github.com/pardeike/Harmony/commit/23c2a2376ba35a31f0eadf0511f6eaf493b9b530#diff-c906413b238a6ac8f812311ee00d10f6R286)

**[5264949](https://github.com/pardeike/Harmony/commit/52649496cc4a8121b185a93b36bd5def7a74981b)**
* Port Traverse edit

**[ad09828](https://github.com/pardeike/Harmony/commit/ad0982837f60a85d15e3582b3dbc9eb61a5ab889)**
* Add `HarmonyPatchType.ReversePatch` as its own type (good idea)
* `HarmonyReversePatchType.Wrapped` to `HarmonyReversePatchType.Snapshot`
    * Plus its implementation in `PatchFunctions`
* Add `Harmony.ReversePatch`
* `ReversePatcher` takes `HarmonyMethod` instead of just `MethodInfo`
    * `Patch` returns the resulting patch 

**[8c2cf479](https://github.com/pardeike/Harmony/commit/8c2cf4793c4c561d650bd36f3ceaeed4d278d41f)**
* Add `PatchProcessor.GetOriginalInstructions`

**[0ae999](https://github.com/pardeike/Harmony/commit/0ae9996ec56e13329bad0fd92fe5ad85c5325e3f)**
* Port the `ldtoken` fix

**[d3c7a06](https://github.com/pardeike/Harmony/commit/d3c7a065b16b95b0265b730ec8cb554a5365b103)**
* Oh god, they merged the empty body patching
    * inb4 "Why does unpatching extern break everything? Why can't I do prefixes? Why no postfixes? Why can't call the original method?"
    * Ignore the change, stick to our implementation that can do everything
* Add sanity check for argument passing into transpilers [like this](https://github.com/pardeike/Harmony/commit/d3c7a065b16b95b0265b730ec8cb554a5365b103#diff-63b15055435b0206f7628f26d678bf88R216)

**General notes**
* Switch to [MonoMod Dev Builds](https://github.com/pardeike/Harmony/commit/fb139307c2ca267aa0f89aa2e3245691c1e58e36#diff-2dc48a4bc6cf919be0c11504e6dcbf81R4)

**Comment by ManlyMarco** [comment]
The 5264949 traverse change is already in, only the tests need to be ported.

**Comment by denikson** [comment]
Harmony 2 master is now ported over in HarmonyX master. Starting from now we'll be frequently merging changes from upstream and adapt for binary compatibility.

This means there will be breaking changes between HarmonyX 2.0 and 2.1, but after that it should be conflict-free.  
HarmonyX 2.1 is already testable as beta on NuGet.
