### ISSUE TITLE
Implement IDisposable in the Harmony class

### ISSUE THREAD

**Issue by ManlyMarco** [BepInEx/HarmonyX#43]
Can be an explicit implementation. All disposing has to do is call UpatchSelf.

This would be useful when working with the disposable pattern, for example when making a plugin that can be hot-reloaded. Currently you have to do this:
```cs
var hi = Harmony.CreateAndPatchAll(typeof(Hooks), typeof(Hooks).FullName);
return Disposable.Create(() => hi.UnpatchSelf());
```
when it could be just this:
```cs
return Harmony.CreateAndPatchAll(typeof(Hooks), typeof(Hooks).FullName);
```
You could use it inside `using` as well but that's a pretty uncommon case.

Example of the disposable pattern to make a plugin reloadable:
```cs
private static readonly List<IDisposable> _cleanupList = new List<IDisposable>();

private void Start()
{
    try
    {
        _cleanupList.Add(RegisterButtons());
        _cleanupList.Add(Hooks.ApplyHooks());
    }
    catch
    {
        OnDestroy();
        throw;
    }
}

private void OnDestroy()
{
    foreach (var disposable in _cleanupList)
    {
        try
        {
            disposable.Dispose();
        }
        catch (Exception ex)
        {
            UnityEngine.Debug.LogException(ex);
        }
    }
}

```

**Comment by ghorsington** [comment]
Sounds good. I added a hidden implementation of `Dispose` now, check 511a1fa1

Or should the `Dispose` be public? I think it's more reasonable to keep it hidden so that you can still use `using` and other `IDisposable` helpers while still encouraging users to use `UnpatchSelf` for common cases.

**Comment by ManlyMarco** [comment]
Nice, thanks. I think it should be private for the reason stated.
