### ISSUE TITLE
Harmony.CreateAndPatchAll - ensure no duplicate guids

### ISSUE THREAD

**Issue by ManlyMarco** [BepInEx/HarmonyX#44]
https://github.com/BepInEx/HarmonyX/blob/master/Harmony/Public/Harmony.cs#L367

There exists a world where Guid.NewGuid() returns the same thing twice for different instances, and it creates a weird bug someone wastes time chasing.

How about adding a check for existing instances and generate a new guid if it already exists?

Alternatively it could use assembly-qualified type name instead. As a bonus it would be much more descriptive when debugging (it would need a dupe check as well).

**Comment by ghorsington** [comment]
Have you managed to replicate this issue specifically? According to MSDN on [`Guid.NewGuid()`](https://docs.microsoft.com/en-us/dotnet/api/system.guid.newguid):

> On Windows, this function wraps a call to the CoCreateGuid function. The generated GUID contains 122 bits of strong entropy.

Moreover, on Unity mono (anything prior to 2020) `NewGuid` actually uses `RandomNumberGenerator` to create the GUID ([source](https://github.com/Unity-Technologies/mono/blob/unity-2020.2-mbe/mcs/class/corlib/System/Guid.cs#L45)) which actually should produce much better randomness. 

If I'd fix anything, I'd probably replace the whole GUID with a direct call to `RandomNumberGenerator` to generate a random string.

**Comment by ManlyMarco** [comment]
It's just theoretical. Using RandomNumberGenerator can still result in getting two of the same value. The odds are astronomical but I'd feel a lot better using this feature if there was no chance of this happening at all.

**Comment by KryziK** [comment]
While technically *possible*, it's called a GUID (globally unique identifier) for a reason. 

So many systems and companies rely on a GUID being unique that we'd have bigger problems if it ever were not.

There is basically no need to check for a duplicate GUID in a worldwide database, let alone a plugin that is likely to be among less than 100 other plugins running in the same process.

> This is a convenient static method that you can call to get a new [Guid](https://learn.microsoft.com/en-us/dotnet/api/system.guid?view=net-7.0). The method creates a Version 4 Universally Unique Identifier (UUID) as described in [RFC 4122, Sec. 4.4](https://datatracker.ietf.org/doc/html/rfc4122#section-4.4). The returned [Guid](https://learn.microsoft.com/en-us/dotnet/api/system.guid?view=net-7.0) is guaranteed to not equal [Guid.Empty](https://learn.microsoft.com/en-us/dotnet/api/system.guid.empty?view=net-7.0).
On Windows, this function wraps a call to the [CoCreateGuid](https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-cocreateguid) function. The generated GUID contains 122 bits of strong entropy.

> The CoCreateGuid function calls the RPC function [UuidCreate](https://learn.microsoft.com/en-us/windows/desktop/api/rpcdce/nf-rpcdce-uuidcreate), which creates a GUID, a globally unique 128-bit integer. Use CoCreateGuid <b>when you need an absolutely unique number that you will use as a persistent identifier in a distributed environment. To a very high degree of certainty, this function returns a unique value – no other invocation, on the same or any other system (networked or not), should return the same value.</b>

**Comment by ManlyMarco** [comment]
Well yes, in practice this is not going to happen, no one's disputing that. I still think it would be worthwhile to at least add the calling assembly name to the generated guid for easier debugging.

**Comment by KryziK** [comment]
For what it's worth, you could pass your own name/GUID to both of these for easier debugging:

```cs
Harmony.CreateAndPatchAll(..., nameHere)
new Harmony.Harmony(nameHere)
