### ISSUE TITLE
[Error : HarmonyX] Valheim with mods 

### ISSUE THREAD

**Issue by OceanRift** [BepInEx/HarmonyX#57]
When I install any mod with ARMOR I don't have a recipes in-game, and this error in console 

[Error  :  HarmonyX] Error while running static void ItemManager.Item::Patch_GetAvailableRecipesFinalizer(System.Collections.Generic.Dictionary<Recipe, BepInEx.Configuration.ConfigEntryBase> __state). Error: System.NullReferenceException: Object reference not set to an instance of an object
  at ItemManager.Item.Patch_GetAvailableRecipesFinalizer (System.Collections.Generic.Dictionary`2[TKey,TValue] __state) [0x0002b] in <086137e6f26547e3a1ecaa29ce4857af>:0
  at (wrapper dynamic-method) Player.DMD<Player::GetAvailableRecipes>(Player,System.Collections.Generic.List`1<Recipe>&)
[Error  :  HarmonyX] Error while running static void ItemManager.Item::Patch_GetAvailableRecipesFinalizer(System.Collections.Generic.Dictionary<System.Reflection.Assembly, System.Collections.Generic.Dictionary<Recipe, BepInEx.Configuration.ConfigEntryBase>> __state). Error: System.NullReferenceException: Object reference not set to an instance of an object
  at ItemManager.Item.Patch_GetAvailableRecipesFinalizer (System.Collections.Generic.Dictionary`2[TKey,TValue] __state) [0x0002e] in <78ef223af5664c6d92390696a3225e9f>:0
  at (wrapper dynamic-method) Player.DMD<Player::GetAvailableRecipes>(Player,System.Collections.Generic.List`1<Recipe>&)
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ItemManager.Item.Patch_GetAvailableRecipesFinalizer (System.Collections.Generic.Dictionary`2[TKey,TValue] __state) (at <086137e6f26547e3a1ecaa29ce4857af>:0)
(wrapper dynamic-method) Player.DMD<Player::GetAvailableRecipes>(Player,System.Collections.Generic.List`1<Recipe>&)
InventoryGui.UpdateCraftingPanel (System.Boolean focusView) (at <035307060cbb4b30b916cd82ebd80490>:0)
InventoryGui.SetupCrafting () (at <035307060cbb4b30b916cd82ebd80490>:0)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Show>(InventoryGui,Container)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Update>(InventoryGui)

**Comment by ghorsington** [comment]
Greetings!

This looks like an issue with the mods you're using. I suggest contacting the mod developers, since HarmonyX is just a genral game-agnostic tool that mods use.

There is nothing that we can do on HarmonyX side about mods, so closing this as not actionable.

PS: Valheim seems to have been updated recently. Updates tend to break mods, so your best bet is to update them or ask mod authors for help.
