### ISSUE TITLE
CodeQL warning: Dispose call on local IDisposable

### ISSUE THREAD

**Issue by MerijnHendriks** [BepInEx/HarmonyX#61]
HarmonyX: 2.9.0, NuGet
NET: 4.7.2
OS: Windows 11 Pro, build 22000.1455

CodeQL reports that `Harmony` should be disposed after usage.
Problem is that `Harmony` doesn't contain a public `Dispose` method.
Since I want my patches to live for the duration of the application's lifetime, an `using` block would be less than ideal.

To reproduce:

1. Create a new console project
2. Replace `Program.cs` with the following:
```cs
using System;
using HarmonyLib;

class Program()
{
    static void Main()
    {
        var id = "test";
        var harmony = new Harmony(id);
        
        if (harmony.HasAnyPatches(id))
        {
            Console.WriteLine("That is impossible!");
        }
    }
}
```
3. Scan for vunerabilities using CodeQL

Attachments:

![codeql warning](https://user-images.githubusercontent.com/54717671/213429148-27890fd7-f906-4c8a-acf1-3dfe73e7888b.png)

**Comment by ManlyMarco** [comment]
UnpatchSelf is equivalent to disposing. You can also cast to IDisposable and call Dispose then. If you don't actually need the patches to be reverted (e.g. the process is exiting anyways) then it's probably better to not dispose the instance at all since all it will do is slow down the exiting.
