### ISSUE TITLE
Writing an empty Transpiler changes the behavior of the patched method

### ISSUE THREAD

**Issue by Meivyn** [BepInEx/HarmonyX#65]
There is currently a bug in Harmony that makes a method behave differently while being patched by a transpiler. This issue was initially encountered by @Aeroluna. 

**It doesn't have to be empty, but I didn't know how to better express this issue.** Feel free to edit the title.

## Reproduce steps

1. Install [Beat Saber](https://store.steampowered.com/app/620980) and [BSIPA](https://github.com/nike4613/BeatSaber-IPA-Reloaded/releases/tag/4.2.1).

2. Make a mod that contains this transpiler returning unchanged instructions.

    ```cs
    [HarmonyPatch(typeof(BeatmapDataLoader), "GetBeatmapDataFromBeatmapSaveData")]
    internal class BeatmapDataLoaderGetBeatmapDataFromBeatmapSaveDataPatch
    {
        private static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
        {
            return instructions;
        }
    }
    ```

3. Add a postfix that logs something when the offending method in the transpiled method runs.

    ```cs
    [HarmonyPatch(typeof(DefaultEnvironmentEventsFactory), nameof(DefaultEnvironmentEventsFactory.InsertDefaultEnvironmentEvents))]
    internal class DefaultEnvironmentEventsFactoryInsertDefaultEnvironmentEventsPatch
    {
        private static void Postfix()
        {
            Plugin.Log.Notice("InsertDefaultEnvironmentEvents");
        }
    }
    ```

5. Put the mod into `Beat Saber\Plugins`.

4. Run the game and start a level.

Alternatively, use the attached plugin: [BSPlugin1.zip](https://github.com/BepInEx/HarmonyX/files/10777794/BSPlugin1.zip)

## Expected behavior

The `DefaultEnvironmentEventsFactory.InsertDefaultEnvironmentEvents` method shouldn't run and the postfix shouldn't log anything.

## Actual behavior 

The `DefaultEnvironmentEventsFactory.InsertDefaultEnvironmentEvents` method runs and the postfix is logging.

## Environment

- **OS:** Windows 11
- **.NET environment:** Unity 2019.4.28 Mono
- **HarmonyX version:** v2.7.0 to latest ([v2.10.1](https://github.com/BepInEx/HarmonyX/releases/tag/v2.10.1) as of this writing)

## Additional information

I made MonoMod dumps for the [unpatched](https://github.com/BepInEx/HarmonyX/files/10778047/Unpatched.zip) and [patched](https://github.com/BepInEx/HarmonyX/files/10778046/Patched.zip) method.

Here's a diff of the patched method, after applying the transpiler:

![image](https://user-images.githubusercontent.com/793322/219976806-aa3dd6d3-fb31-452f-89c6-5bc081798c06.png)

A [workaround](https://github.com/Aeroluna/CustomJSONData/commit/dd99793c61e68d73eab3c40a381fa64e3ef14dc1) has been found, which consists to add a `Nop` instruction after the `Leave` instruction. By using the same workaround on this test case, the resulting method is exactly the same as the original, according to the dumps.

**Comment by Windows10CE** [comment]
How are you getting a MonoMod dump for the method without patching it? Are there other mods at play here? It seems very odd that adding a Nop inside a finally block would change a branch instruction halfway up the IL. I would try to investigate this myself, but that's a bit difficult without a VR headset to use.

**Comment by Meivyn** [comment]
Sorry, I meant "unpatched" as in "before patch". MonoMod dumps both. 

To make these dumps, I didn't use any mod other than the provided one.

**Comment by ManlyMarco** [comment]
Can you turn on full harmony debug logging and send the log? Not sure how it's done in that launcher. Adding [HarmonyDebug] attribute to the patches might be enough.

**Comment by Meivyn** [comment]
I suppose that you are talking about IL debug? Then here you go [_latest.log](https://github.com/BepInEx/HarmonyX/files/10781549/_latest.log)

**Comment by mgreter** [comment]
We are experiencing the same issue after 7 Days to Die updated HarmonyX with A21 to 2.10.0.0.
I don't have much to add yet. Trying to see if I can find more info to add to this issue here later.
FWIW here the full reproduction case for 7 Days to Die A21 (b317):
```cs
[HarmonyPatch(typeof(ItemClassesFromXml), "parseItem")]
static class ItemClassesFromXmlParseItem
{
    static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions) => instructions;
    static void Postfix() => Log.Out("++ Postfix for ItemClassesFromXml.parseItem called");
    static void Prefix() => Log.Out("++ Prefix for ItemClassesFromXml.parseItem called");
}
```
Pre/Postfix still work as expected, but when transpiler patch is active, game will throw in the original method!

**Comment by mgreter** [comment]
Here are some log files from adding the [HarmonyDebug] flag.

With transpiler enabled: [patch.bad.log](https://github.com/BepInEx/HarmonyX/files/11781243/patch.bad.log) (crash) and only with pre/postfix: [patch.ok.log](https://github.com/BepInEx/HarmonyX/files/11781244/patch.ok.log) (working).

Beside some address changes, there were a few additional OPs added in the bad version related to try/catch!?

![image](https://github.com/BepInEx/HarmonyX/assets/282293/98631635-03fc-4b86-a1b1-f1a80dc6daa7)

![image](https://github.com/BepInEx/HarmonyX/assets/282293/366e2cb1-cc88-4171-b5f6-8768d4ee680f)

**Comment by mgreter** [comment]
After some try and error I found at least what seems to be the culprit.
I basically disabled applying the patches, which still errors when a transpiler is there:
```cs
private void WriteTranspilers()
{
	if (transpilers.Count == 0)
		return;

	Logger.Log(Logger.LogChannel.Info, () => $"Transpiling {original.FullDescription()}", debug);

	// Create a high-level manipulator for the method
	var manipulator = new ILManipulator(ctx.Body, debug);

	// Add in all transpilers
	// foreach (var transpiler in transpilers)
	//	 manipulator.AddTranspiler(transpiler.method);

	// Write new manipulated code to our body
	manipulator.WriteTo(ctx.Body, original);
}
```

Since this crashed, I went into the `ILManipulator.WriteTo`.
There I simply disabled `body.ExceptionHandlers.Clear();` et voila.
With that changes applied the method seems to run as intended.

```cs
// Clean up the body of the target method
body.Instructions.Clear();
// body.ExceptionHandlers.Clear();
```

Of course no idea what the side effects of this change may be.

**Comment by mgreter** [comment]
So finally it seems I found the the specifics that cause it to fail for the given example

```cs
// We need to handle exception handler opcodes specially because ILProcessor emits them automatically
// Case 1: leave + start or end of exception block => ILProcessor generates leave automatically
if ((cur.opcode == SRE.OpCodes.Leave || cur.opcode == SRE.OpCodes.Leave_S) &&
		(cur.blocks.Count > 0 || next?.blocks.Count > 0))
	goto mark_block;
// Case 2: endfilter/endfinally and end of exception marker => ILProcessor will generate the correct end
if ((cur.opcode == SRE.OpCodes.Endfilter || cur.opcode == SRE.OpCodes.Endfinally) && cur.blocks.Count > 0)
	goto mark_block;
```

When this part is disabled, it seems the original functions works again as expected.
Of course I have no idea why it was added in the first place, so probably not a proper fix!

**Comment by mgreter** [comment]
FWIW I've added an alternative cleanup for duplicate leave jumps:

```cs
for (int i = 0; i < body.Instructions.Count - 1; i++)
{
	// Find two leave instructions in a row to clean up
	if (body.Instructions[i].OpCode != OpCodes.Leave &&
			body.Instructions[i].OpCode != OpCodes.Leave_S) continue;
	if (body.Instructions[i + 1].OpCode != OpCodes.Leave &&
			body.Instructions[i + 1].OpCode != OpCodes.Leave_S) continue;
	if (body.Instructions[i].Offset != body.Instructions[i + 1].Offset)
		Logger.Log(Logger.LogChannel.Warn, () =>
			"Found consecutive leave ops that don't agree");
	body.Instructions.RemoveAt(i + 1);
}
```

Now the IL code seems to agree where to jump after patching vs original.
Again, not sure what the original intent was to remove the original "leaves".
But it seems the ones inserted by `ILProcessor` are wrong sometimes!?

Hope with all this info we can get a proper fix in a reasonable time frame 🤞

**Comment by ManlyMarco** [comment]
@ghorsington added the leave hack in https://github.com/BepInEx/HarmonyX/commit/506d4d2cd210bcd2cf044ff64a91737a842b8e42
He hasn't been active in a while so I wouldn't count on a fast fix unless you can spin up a PR.

**Comment by mgreter** [comment]
I of course can spin up a PR that fixes my issue, but not 100% sure it would break/regress the other case :-/
For that I don't have enough insight what the proper fix for that would be.
FWIW I've created https://github.com/BepInEx/HarmonyX/pull/77, so let's see 🤞

**Comment by Meivyn** [comment]
> @ghorsington added the leave hack in [506d4d2](https://github.com/BepInEx/HarmonyX/commit/506d4d2cd210bcd2cf044ff64a91737a842b8e42), if I remember correctly it was necessary to fix compatibility with certain transpliers that worked in older versions of harmony. There's probably a discussion related to this on the BepInEx discord server if you care to search the haystack. He hasn't been active in a while so I wouldn't count on a fast fix unless you can spin up a PR.

The discussion in question: https://discord.com/channels/623153565053222947/624275540844478474/913136287488307281
