### ISSUE TITLE
Skipping a patch when a method isnt found

### ISSUE THREAD

**Issue by YakovAU** [BepInEx/HarmonyX#98]
There are situations in a project with alot of patches where the same DLL will be used on both a dedicated server and client. The code is mostly the same on both, though some methods are missing.
To avoid separate distributions, is it possible to have a feature added that PatchAll will 'skip' a patch if a method is not found? Perhaps done with an annotation?
Thank you for your time.

**Comment by ManlyMarco** [comment]
Duplicate of #47
